# Generated by Django 3.0.8 on 2021-01-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210127_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_liked',
        ),
    ]
