# Generated by Django 3.0.8 on 2021-01-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210111_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Post date'),
        ),
    ]
