# Generated by Django 3.0.8 on 2021-01-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_user_liked'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post_likes',
            constraint=models.UniqueConstraint(fields=('post_id', 'user_liked'), name='unique_post_like'),
        ),
    ]
